sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hlpjzx2003
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tGn8HFc4a4KBafkRRDU
    access-key-secret: wKvQv7eSDAiCMJwHnguNA3IGISvGbz
    bucket-name: sky-take-out-jzx
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wxc6671f295423b7bf
    secret: 049a943f02f725dc1ce2270534243809